events {}

http {
    upstream devops_api {
        server api1:8000;
        server api2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://devops_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}